from tkinter import *
root = Tk()
myButton = Button(root, text="sin", padx=18,pady=18).grid(row=1, column=1)
myButton = Button(root, text="cos", padx=18,pady=18).grid(row=1, column=2)
myButton = Button(root, text="tan", padx=18,pady=18).grid(row=1, column=3)
myButton = Button(root, text="rad", padx=18,pady=18).grid(row=1, column=4)
myButton = Button(root, text="deg", padx=18,pady=18).grid(row=1, column=5)
myButton = Button(root, text="log", padx=18,pady=18).grid(row=2, column=1)
myButton = Button(root, text="ln", padx=18,pady=18).grid(row=2, column=2)
myButton = Button(root, text='(', padx=18,pady=18).grid(row=2, column=3)
myButton = Button(root, text=')', padx=18,pady=18).grid(row=2, column=4)
myButton = Button(root, text="inv", padx=18,pady=18).grid(row=2, column=5)
myButton = Button(root, text='!', padx=20,pady=20).grid(row=3, column=1)
myButton = Button(root, text="Ac", padx=18,pady=18).grid(row=3, column=2)
myButton = Button(root, text='%', padx=20,pady=20).grid(row=3, column=3)
myButton = Button(root, text="C", padx=20,pady=20).grid(row=3, column=4)
myButton = Button(root, text='/', padx=20,pady=20).grid(row=3, column=5)
myButton = Button(root, text='^', padx=20,pady=20).grid(row=4, column=1)
myButton = Button(root, text=7, padx=20,pady=20).grid(row=4, column=2)
myButton = Button(root, text=8, padx=20,pady=20).grid(row=4, column=3)
myButton = Button(root, text=9, padx=20,pady=20).grid(row=4, column=4)
myButton = Button(root, text='*', padx=20,pady=20).grid(row=4, column=5)
myButton = Button(root, text="sqrt", padx=16,pady=16).grid(row=5, column=1)
myButton = Button(root, text=4, padx=20,pady=20).grid(row=5, column=2)
myButton = Button(root, text=5, padx=20,pady=20).grid(row=5, column=3)
myButton = Button(root, text=6, padx=20,pady=20).grid(row=5, column=4)
myButton = Button(root, text='-', padx=20,pady=20).grid(row=5, column=5)
myButton = Button(root, text="pi", padx=18,pady=18).grid(row=6, column=1)
myButton = Button(root, text=1, padx=20,pady=20).grid(row=6, column=2)
myButton = Button(root, text=2, padx=20,pady=20).grid(row=6, column=3)
myButton = Button(root, text=3, padx=20,pady=20).grid(row=6, column=4)
myButton = Button(root, text='+', padx=20,pady=20).grid(row=6, column=5)
myButton = Button(root, text="e", padx=20,pady=20).grid(row=7, column=1)
myButton = Button(root, text=00, padx=20,pady=20).grid(row=7, column=2)
myButton = Button(root, text=0, padx=20,pady=20).grid(row=7, column=3)
myButton = Button(root, text='.', padx=20,pady=20).grid(row=7, column=4)
myButton = Button(root, text='=', padx=20,pady=20).grid(row=7, column=5)
root.mainloop()